site_name: Projecto FOG Hugo
nav:
- Introduccion: index.md
- Sprint1: Sprint1.md
- Sprint2: Sprint2.md
- Sprint3: Sprint3.md
- Sprint4: Sprint4.md
- Sprint5: Sprint5.md
- Sprint1Windows: Sprint1W.md
theme:
  name: readthedocs
  custom_dir: overrides
extra_css:
  - styles/custom.css
